### ISSUE TITLE
List of existing reference package with ID grouped by geochemical process

### ISSUE THREAD

**Issue by stephan-koenig** [EDUCE-UBC/MICB425#11]
Due Mar 24

- [x] Create list based on https://github.com/hallamlab/RefPkgs/wiki/refpkgs
- [x] Improve [refpkgs.Rmd](https://github.com/EDUCE-UBC/MICB425/blob/development/child_Rmds/refpkgs.Rmd)

**Comment by stephan-koenig** [comment]
Not sure if @janstett can also help with this?

**Comment by janstett** [comment]
@stephan-koenig, is this the list for the students to choose from?

**Comment by stephan-koenig** [comment]
@janstett,  just clarified the title, I meant the list of already available reference packages.

**Comment by janstett** [comment]
@cmorganl should have a comprehensive list of these.

**Comment by stephan-koenig** [comment]
We probably could base it on this?

https://github.com/hallamlab/RefPkgs/wiki/refpkgs

**Comment by janstett** [comment]
Yes, however, you might want to focus on the functional packages rather than the taxonomic packages (the ones that start with PF)

**Comment by cmorganl** [comment]
Yes, that is the most up-to-date list of reference packages. It does include all versions (e.g. seed, updated) for some reference packages. How do you want the list formatted and where is the list to be entered?

**Comment by stephan-koenig** [comment]
The best would be as an `Rmd` file. I would like to combine the name with the link to GitHub.

I started with your `md` file but did not want to spend too much time on figuring out how to edit your table programmatically to get the hyperlinks and used the new RStudio WYSIWIG editor to carry me some of the way. Unfortunately, the visual editor uses pandoc's grid table, and it looks very confusing in plain text. Also, it seems to me it uses the longest word to determine the column width, and that throws the table layout off due to the long hyperlinks.
<img width="1292" alt="refpkgs_table" src="https://user-images.githubusercontent.com/11433347/110431425-a5b22d00-8062-11eb-82f8-f9a34ca775b8.png">

I think an explicit column for the pathway would be great. Maybe we can drop the TreeSAPP version on the Date column, but I am unsure if the students might need that information. Check out the current version of the bookdown on the 'development' branch in the "Tools" chapter. The table itself is saved separately in `child_Rmds/refpkgs.Rmd`
