### ISSUE TITLE
Merge of julia_branch into development reverted too far

### ISSUE THREAD

**Issue by cmorganl** [EDUCE-UBC/MICB425#37]
I'm unable to merge development into master as the commit [1a3ce39db2accc921536deb05fb74dee47ece550](https://github.com/EDUCE-UBC/MICB425/commit/1a3ce39db2accc921536deb05fb74dee47ece550) reverted all recent changes to the bookdown. For example, all fastq and fasta files have been wiped clean from `data/` and are essential to the `treesapp abundance` tutorial.

I think the `development` branch will need to be reset to `main` and all changes should be included in a new pull request into `development`. There may be a better way but that's the simplest method I can think of to ensure no work is lost.

**Comment by janstett** [comment]
Ok, let me know when I can pull the reset version of the  development branch and so I can redo my pull request. I'm sorry, I merged my branch into instead of doing a pull, then I panicked and tried to revert my changes and I messed things.

**Comment by stephan-koenig** [comment]
@cmorganl , have you pushed again Julia's changes to 'development'? I had it reset to my last commit (8d29dc054b34b1ee57e60ee10ff3cbf4419e8781), but now her commits are back. Everyone needs to reset their 'development' branch, i.e. while on the 'development' branch `git reset --hard origin/development` after the reset.

@cmorganl, Is your latest commit 9ad3c1dcb619c0c2792e9029095278fd8e974a23 on any other branch than 'development'?

**Comment by janstett** [comment]
Sorry, I think I pushed them back into dev

**Comment by janstett** [comment]
@stephan-koenig  and @cmorganl Hey, before I do anything stupid again, on my local machine, I ran git reset --hard origin/development, it says HEAD is now at 290aab8 Make capstone refpkg selection more clear. Do I need to do another pull request for julia_branch to develoment, or am I done?

**Comment by stephan-koenig** [comment]
Did you just reset now?

**Comment by janstett** [comment]
I think we're all clear

**Comment by stephan-koenig** [comment]
Did you already add the new directory with the concatenated Saanich data to the description?

**Comment by janstett** [comment]
Yes, I see those changes in commit 6bbca084b111237434a74aec0638799bc39a491a
