### ISSUE TITLE
Provide iTOL licenses

### ISSUE THREAD

**Issue by stephan-koenig** [EDUCE-UBC/MICB425#7]
- [x] Share information for lab license with Steven, Stephan and Sean
- [x] Request dedicated licenses for MICB425 students

**Comment by cmorganl** [comment]
We've received instructions from the iTOL maintainer, Ivica Letunić. The student or group accounts need to be created first and then we are to send him the usernames. He will add a free subscription to the accounts.
Maybe it would be best to create an account for each group? If students would like to have their own workspace they are free to do so under their group's account.

How many groups are there?

**Comment by stephan-koenig** [comment]
Great! I talked to Steven and Sean, and we decided to go with 9 groups. If you don't mind, would you please set them up on iTOL with the following naming convention `MICB425_2020W2_group_<number>` (with `<number>` being a single digit from 1--9) and then request the free subscription?

**Comment by cmorganl** [comment]
Can you shorten it up a bit? iTOL requires login names to be between 4 and 15 characters.

**Comment by stephan-koenig** [comment]
Let's do `MICB425_grp_<number>`!
