### ISSUE TITLE
Data description and previous processing

### ISSUE THREAD

**Issue by stephan-koenig** [EDUCE-UBC/MICB425#8]
Due Mar 24

Send to @stephan-koenig by email or edit `data.Rmd` file and deposit images in `images` folder.

- [x] General introduction of Saanich Inlet (maybe @stephan-koenig or @nevetsmallah
- [x] Give location on server
- [x] Provide methods for wet lab
- [x] Provide methods for SAG and MAG assembly
- [x] Provide description of checkM steps
- [x] Provide version numbers for all software tools
- [x] Provide images for wet lab and *in silico* workflows

**Comment by stephan-koenig** [comment]
@janstett I found some older text from a previous MICB425 project description for the wet lab steps. Please check out `data .Rmd` on the 'development' branch and adjust/correct as you see fit. Below I also included the text.

"Water was collected from various depths at Saanich Inlet and filtered through a 0.22 µm Sterivex filter to collect biomass. Total genomic DNA and RNA were extracted from these filters. RNA was reversed transcribed into cDNA and both genomic DNA and cDNA were used in the construction of shotgun Illumina libraries. Sequencing data were generated on the Illumina HiSeq platform with **2x150bp** technology. For more in-depth sampling and sequencing methods, please see @Hawley.2017. "

**Comment by janstett** [comment]
Hi @stephan-koenig, that description is the one I wrote last year for the DNA and RNA, it'll definitely work here.
