### ISSUE TITLE
Tutorial for golden data

### ISSUE THREAD

**Issue by stephan-koenig** [EDUCE-UBC/MICB425#9]
Goal: Create activities on how to critically select data to use for building a TreeSAPP reference package. File: `golden_data.Rmd`

- [x] Add information from [TreeSAPP create wiki](https://github.com/hallamlab/TreeSAPP/wiki/Building-reference-packages-with-TreeSAPP)
- [x] Introduce common sources of golden data
- [x] Include steps for QC of reference sequences
- [ ] Create workflow with decision points for keeping/rejecting sequences
- [x] Create Problem set 5 about golden data
- [x] Create tutorial on bookdown

**Comment by cmorganl** [comment]
Am I responsible for developing problem set 5?
